apps/article/views.py
from flask import Blueprint, render_template
from flask import url_for, g
from flask import jsonify, request
from flask import redirect, session
from ..utils import upload_to_qiniu, delete_to_qiniu
from .models import Article, Tag, Comment
from ..user.models import Photo, User

article_bp = Blueprint('article', __name__, url_prefix='/article')


@article_bp.route('/publish', methods=['GET', 'POST'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        tag_id = request.form.get('tag')
        content = request.form.get('content')
        article = Article()
        article.title = title
        article.tag_id = tag_id
        article.content = content
        article.user_id = g.user.user_id
        article.yes()
        return redirect(url_for('user.index'))
    return redirect(url_for('user.user_center'))


@article_bp.route('/detail')
def article_detail():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    user = None
    tags = Tag.query.all()
    uid = session.get('uid', None)
    if uid:
        user = User.query.get(uid)
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter(Comment.art_id == article_id).order_by(-Comment.cmt_time).paginate(page=page, per_page=5)

    return render_template('article/detail.html', article=article, tags=tags, user=user, comments=comments)


@article_bp.route('/love')
def article_love():  # 点赞
    aid = request.args.get('aid', type=int)
    t = request.args.get('t', type=int)
    article = Article.query.get(aid)  # type: Article

    if t == 1:
        article.love_num -= 1
    else:
        article.love_num += 1
    article.yes()
    return jsonify({
        'num': article.love_num
    })


@article_bp.route('/photo', methods=['GET', 'POST'])
def photo_album():
    if request.method == 'POST':
        pic = request.files.get('photo')
        ret, info = upload_to_qiniu(pic)
        if info.status_code == 200:
            photo = Photo()
            photo.photo_name = ret['key']
            photo.user_id = g.user.user_id
            photo.yes()
            return redirect(url_for('user.user_center'))
        return 'post'
    return 'get'


@article_bp.route('/photo_del')
def delete_photo():
    pid = request.args.get('pid', type=int)
    photo = Photo.query.get(pid)  # type:Photo
    info = delete_to_qiniu(photo.photo_name)
    if info.status_code == 200:
        photo.ono()
        return redirect(url_for('user.user_center'))
    else:
        return '失败了'


@article_bp.route('/pub_cmt', methods=['GET', 'POST'])
def publish_comment():
    if request.method == 'POST':
        aid = request.form.get('aid')
        cmt_ctt = request.form.get('comment')
        user_id = g.user.user_id
        cmt = Comment()
        cmt.comment = cmt_ctt
        cmt.user_id = user_id
        cmt.art_id = aid
        cmt.yes()
        return redirect(url_for('article.article_detail') + '?aid=' + aid)
    return redirect('/')


@article_bp.route('/tag')
def tag_search():
    tags = Tag.query.all()
    user = None
    uid = session.get('uid', None)
    if uid:
        user = User.query.get(uid)
    tid = request.args.get('tid', type=int)
    page = request.args.get('page', 1, type=int)

    articles = Article.query.filter(Article.tag_id == tid).paginate(page=page, per_page=3)

    return render_template('article/tag.html', **locals())


@article_bp.route('delete_cmt')
def delete_comment():
    cmt_id = request.args.get('cmt_id')
    if cmt_id:
        cmt = Comment.query.get(cmt_id)
        cmt.ono()
        return redirect(url_for('user.user_center'))

apps/user/views.py
import os.path
from flask import Blueprint, render_template
from flask import url_for, g, current_app
from flask import jsonify, request
from flask import redirect, session
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from ..exts import mail
from ..cfg import Config
from random import randint
from .models import User, Photo, AboutMe, MessageBoard
from ..article.models import Tag, Article

user_bp = Blueprint('user', __name__, url_prefix='/user')

allowed_path = [
    '/user/center.html', '/user/update', '/article/publish',
    '/article/photo', '/user/photos.html', '/article/photo_del',
    '/article/pub_cmt', '/user/aboutme', '/user/showme',
]


@user_bp.before_app_request
def before_you_request():
    if request.path in allowed_path:
        uid = session.get('uid')
        if not uid:
            return render_template('user/login.html')
        else:
            user = User.query.get(uid)
            g.user = user


@user_bp.after_app_request
def after_you_request(response):
    return response


@user_bp.route('/', endpoint='index')
def index():
    uid = session.get('uid')
    page = request.args.get('page', 1, type=int)
    tags = Tag.query.all()
    pagination = Article.query.order_by(-Article.pub_time).paginate(page=page, per_page=3)
    if uid:
        user = User.query.get(uid)
        return render_template('user/index.html', user=user, pagination=pagination, tags=tags)
    else:
        return render_template('user/index.html', pagination=pagination, tags=tags)


@user_bp.route('/register.html', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        if request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            pwd = request.form.get('pwd')
            phone = request.form.get('phone')
            email = request.form.get('email')
            if password == pwd:
                user = User()
                user.username = username
                user.password = password
                user.phone = phone
                user.email = email
                user.yes()
                return redirect('/')
    return render_template('user/register.html')


@user_bp.route('/protocol')
def must_protocol():
    return render_template('user/bwtk.html')


@user_bp.route('/verify_phone')
def check_phone():
    phone_num = request.args.get('phoneNum')
    user = User.query.filter(User.phone == phone_num).all()
    if user:
        return jsonify({
            'status': 400,
            'msg': '此号码已被注册',
            'url': f'{request.url}',
        })
    else:
        return jsonify({
            'status': 200,
            'msg': '此号码可用',
            'url': f'{request.url}',
        })


@user_bp.route('/verify_email')
def check_email():
    email = request.args.get('email')
    user = User.query.filter(User.email == email).all()
    if user:
        return jsonify({
            'code': 400,
            'msg': '该邮箱已被注册',
            'url': f'{request.url}',
        })
    else:
        return jsonify({
            'code': 200,
            'msg': '该邮箱可用',
            'url': f'{request.url}',
        })


def save_captcha_to_session(email, captcha):
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    token = s.dumps(captcha, salt='email-captcha')
    session[f'captcha_{email}'] = token


def verify_captcha_from_session(email, captcha):
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    token = session.get(f'captcha_{email}')
    try:
        data = s.loads(token, salt='email-captcha', max_age=300)  # 假设验证码5分钟内有效
        return data == captcha
    except SignatureExpired:
        return False
    except BadSignature:
        return False


@user_bp.route('/email_capcha')
def send_email_capcha():
    email = request.args.get('email')
    random_num = randint(100000, 999999)
    save_captcha_to_session(email, random_num)

    try:
        msg = Message(
            subject="邮箱验证码",
            recipients=[email, ],
            html=f"""<table><tbody><tr height="40">
        <td style="padding-left:25px;padding-right:25px;font-size:18px;font-family:'微软雅黑','黑体',arial;">
            尊敬的 <a href="mailto:{email}" rel="noopener" target="_blank">{email}</a> ：
        </td></tr><tr height="15"><td></td></tr><tr height="30">
        <td style="padding-left:55px;padding-right:55px;font-family:'微软雅黑','黑体',arial;font-size:14px;line-height:20px;">
            您的账户<a href="{email}" rel="noopener" target="_blank">{email}</a> 
            正在获取身份验证, 验证码 {random_num} , 5 分钟内有效。
            </td></tr><tr height="20"><td></td></tr>
            <tr><td style="padding-left:55px;padding-right:55px;font-family:'微软雅黑','黑体',arial;font-size:14px;">
            此致<br>本站作者</td></tr><tr height="50"><td></td></tr></tbody></table>"""
        )
        mail.send(message=msg)
        return jsonify({
            'status': 200,
            'msg': '验证码发送成功'
        })
    except Exception as e:
        return jsonify({
            'status': 400,
            'msg': '验证码发送失败'
        })


@user_bp.route('/login.html', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        f = request.args.get('f')
        if f == '1':
            username = request.form.get("username")
            password = request.form.get("password")
            users = User.query.filter(User.username == username).all()
            for user in users:
                if user.check_pwd(password):
                    session['uid'] = user.user_id
                    return redirect('/')
            else:
                return render_template('user/login.html', msg='用户名或密码有误')

        elif f == '2':
            email = request.form.get('email')
            random_num = request.form.get('yzm', type=int)
            user = User.query.filter(User.email == email).first()
            if user and verify_captcha_from_session(email, random_num):
                session['uid'] = user.user_id
                return redirect(url_for('user.index'))
            else:
                return render_template('user/login.html', msg='邮箱或验证码有误')
    return render_template('user/login.html')


@user_bp.route('/logout')
def logout():
    session.clear()
    return redirect('/')


@user_bp.route('/center.html')
def user_center():
    tags = Tag.query.all()
    photos = Photo.query.filter(Photo.user_id == g.user.user_id).all()
    return render_template('user/center.html', user=g.user, tags=tags, photos=photos)


image_suffix = ['jpg', 'gif', 'png', 'webp']


@user_bp.route('/update', methods=['GET', 'POST'])
def user_update():
    if request.method == 'POST':
        username = request.form.get('username')
        phone = request.form.get('phone')
        email = request.form.get('email')
        icon = request.files.get('icon')  # type:FileStorage
        avatar_path = None
        if icon:
            icon_name = icon.filename
            suffix = icon_name.split('.')[1]
            if suffix.lower() in icon_name:
                icon_name = secure_filename(icon_name)
                file_path = os.path.join(Config.ICON_DIR, icon_name)
                icon.save(file_path)
                avatar_path = os.path.join('uploads/icon/', icon_name)
            else:
                return render_template('user/center.html', user=g.user, msg='图片格式不对')
        else:
            avatar_path = g.user.avatar if g.user.avatar else None
        user = g.user
        user.username = username
        user.phone = phone
        user.email = email
        user.avatar = avatar_path
        user.yes()
        return redirect(url_for('user.user_center'))
    else:
        return render_template('user/center.html')


@user_bp.route('/photos.html')
def my_photo():
    page = request.args.get('page', 1, type=int)
    photos = Photo.query.paginate(page=page, per_page=1)
    return render_template('user/photos.html', photos=photos, user=g.user)


@user_bp.route('/aboutme', methods=['GET', 'POST'])
def about_me():
    content = request.form.get('about')
    print(content)
    has_me = AboutMe.query.filter_by(user_id=g.user.user_id).first()
    if has_me.content:
        has_me.content = content
        has_me.yes()
    else:
        me = AboutMe()
        me.content = content
        me.user_id = g.user.user_id
        me.yes()
    return render_template('user/aboutme.html', user=g.user)


@user_bp.route('/showme')
def show_about_me():
    return render_template('user/aboutme.html', user=g.user)


@user_bp.route('/board', methods=['GET', 'POST'])
def show_board():
    uid = session.get('uid', None)
    user = None
    if uid:
        user = User.query.get(uid)
    page = request.args.get('page', 1, type=int)
    boards = MessageBoard.query.order_by(-MessageBoard.bd_time).paginate(page=page, per_page=5)
    if request.method == 'POST':
        content = request.form.get('board')
        mb = MessageBoard()
        mb.content = content
        if uid:
            mb.user_id = uid
        mb.yes()
        return redirect(url_for('user.show_board'))
    return render_template('user/board.html', user=user, boards=boards)


@user_bp.route('/del_bd')
def delete_board():
    bid = request.args.get('bid', type=int)
    if bid:
        mb = MessageBoard.query.get(bid)
        mb.ono()
        return redirect(url_for('user.user_center'))

templates/base.html
{% block doc -%}
    <!DOCTYPE html>
    <html{% block html_attribs %}{% endblock html_attribs %}>
    {%- block html %}
        <head>
            {%- block head %}
                <meta charset="utf-8">
                <meta name="viewport"
                      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
                <meta http-equiv="X-UA-Compatible" content="ie=edge">
                {%- block metas -%}{%- endblock metas -%}
                <title>{% block title %}{{ title|default('Flask') }}{% endblock title %}</title>
                <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
                <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
                <link rel="stylesheet" href="{{ url_for('static', filename='iconfont/iconfont.css') }}">
                <script src="{{ url_for('static', filename='js/base/base.js') }}"></script>
                <script src="{{ url_for('static', filename='js/base/alpha.js') }}"></script>
                <script src="{{ url_for('static', filename='js/form-serialize.js') }}"></script>
                <script src="{{ url_for('static', filename='js/jquery-3.7.1.js') }}"></script>
                {%- block styles %}{%- endblock styles %}
                {%- block links -%}{%- endblock -%}
            {%- endblock head -%}
        </head>
        <body{% block body_attribs %}{% endblock body_attribs %}>
        {%- block body -%}
            <canvas></canvas>
            {% block nav %}
                <nav class="nav">
                    <div class="w">
                        <div class="container-fluid">
                            <div class="logo"> <!--111-->
                                <h1><a href="">迷你博客</a></h1>
                            </div>
                            <div class="collapse navbar-collapse">
                                <!--333333333333-->
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a href="/">首页</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('user.show_about_me') }}">关于我</a>
                                    </li>
                                    <li class="dropdown dropdown">
                                        <a href="" class="dropdown-toggle">文章分类</a>
                                        <i class="iconfont">&#xe83b;</i>
                                        <ul class="dropdown-menu">
                                            {% for tag in tags %}
                                                <li class="dropdown-item">
                                                    <a href="{{ url_for('article.tag_search') }}?tid={{ tag.tag_id }}">{{ tag.name }}</a>
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('user.my_photo') }}">我的相册</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="{{ url_for('user.show_board') }}">留言板</a>
                                    </li>
                                    <li>
                                        <form action="" class="nav-search">
                                            <input type="search" name="search" placeholder="Search">
                                            <button id="search" class="btn-search" type="button">Search</button>
                                        </form>
                                    </li>
                                </ul>
                                <!--444444444444-->
                                <div class="nav-user">
                                    <ul>
                                        {% if user %}
                                            <li>
                                                <img src="{% if user.avatar %}
                                                	{{ url_for('static',filename=user.avatar) }}
                                                {% else %}
                                                	{{ url_for('static',filename='images/tx.png') }}
                                                {% endif %} " alt="">
                                            </li>
                                            <li class="dropdown dropdown">
                                                <a href="" class="dropdown-toggle">欢迎 {{ user.username }}</a>
                                                <i class="iconfont">&#xe83b;</i>
                                                <ul class="dropdown-menu">
                                                    <li class="dropdown-item"><a
                                                            href="{{ url_for('user.user_center') }}">用户中心</a></li>
                                                    <li class="dropdown-item"><a href="{{ url_for('user.logout') }}">退出登录</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        {% else %}
                                            <li>
                                                <a href="{{ url_for('user.login') }}">登录</a>
                                            </li>
                                            <li>
                                                <a href="{{ url_for('user.register') }}">注册</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </nav>
            {%- endblock nav -%}

            {% block contents -%}

                {% block content %}
                    <h1>Hello Flask</h1>
                {% endblock content -%}

                {% block footer %}
                    <footer class="footer">
                        <div class="footer_links">
                            <a href="">关于我们</a>
                            <span>|</span>
                            <a href="">联系我们</a>
                            <span>|</span>
                            <a href="">招聘人才</a>
                            <span>|</span>
                            <a href="">友情链接</a>
                        </div>
                        <p class="copyright">
                            CopyRight © 2004~2024&emsp;四川泸州沃痕牛逼科技有限公司&emsp;All Rights Reserved<br>
                            电话：010-110120119 京ICP备1008668号
                        </p>
                    </footer>
                {%- endblock footer -%}

            {%- endblock contents -%}

            {% block scripts -%}{%- endblock scripts -%}

        {%- endblock body -%}
        </body>
    {%- endblock html -%}
    </html>
{% endblock doc -%}