apps/article/models.py
from datetime import datetime
from ..utils import BaseModel
from ..exts import db


class Tag(BaseModel):
    __tablename__ = 'tb_tag'
    tag_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(16), nullable=False)
    articles = db.relationship('Article', backref='tag')


class Article(BaseModel):
    __tablename__ = 'tb_article'
    art_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(50), nullable=False)
    content = db.Column(db.Text, nullable=False)
    pub_time = db.Column(db.DateTime, default=datetime.now)
    click_num = db.Column(db.Integer, default=0)
    save_num = db.Column(db.Integer, default=0)
    love_num = db.Column(db.Integer, default=0)
    user_id = db.Column(db.Integer, db.ForeignKey('tb_user.user_id'), nullable=False)
    comments = db.relationship('Comment', backref='article')
    tag_id = db.Column(db.Integer, db.ForeignKey('tb_tag.tag_id'), nullable=False)


class Comment(BaseModel):
    __tablename__ = 'tb_comment'
    cmt_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    comment = db.Column(db.String(255), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('tb_user.user_id'))
    art_id = db.Column(db.Integer, db.ForeignKey('tb_article.art_id'))
    cmt_time = db.Column(db.DateTime, default=datetime.now)

apps/article/views.py
from flask import Blueprint, render_template
from flask import url_for, g
from flask import jsonify, request
from flask import redirect, session
from ..utils import upload_to_qiniu, delete_to_qiniu
from .models import Article, Tag, Comment
from ..user.models import Photo, User

article_bp = Blueprint('article', __name__, url_prefix='/article')


@article_bp.route('/publish', methods=['GET', 'POST'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        tag_id = request.form.get('tag')
        content = request.form.get('content')
        article = Article()
        article.title = title
        article.tag_id = tag_id
        article.content = content
        article.user_id = g.user.user_id
        article.yes()
        return redirect(url_for('user.index'))
    return redirect(url_for('user.user_center'))


@article_bp.route('/detail')
def article_detail():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    user = None
    tags = Tag.query.all()
    uid = session.get('uid', None)
    if uid:
        user = User.query.get(uid)
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter(Comment.art_id == article_id).order_by(-Comment.cmt_time).paginate(page=page, per_page=5)

    return render_template('article/detail.html', article=article, tags=tags, user=user, comments=comments)


@article_bp.route('/love')
def article_love():  # 点赞
    aid = request.args.get('aid', type=int)
    t = request.args.get('t', type=int)
    article = Article.query.get(aid)  # type: Article

    if t == 1:
        article.love_num -= 1
    else:
        article.love_num += 1
    article.yes()
    return jsonify({
        'num': article.love_num
    })


@article_bp.route('/photo', methods=['GET', 'POST'])
def photo_album():
    if request.method == 'POST':
        pic = request.files.get('photo')
        ret, info = upload_to_qiniu(pic)
        if info.status_code == 200:
            photo = Photo()
            photo.photo_name = ret['key']
            photo.user_id = g.user.user_id
            photo.yes()
            return redirect(url_for('user.user_center'))
        return 'post'
    return 'get'


@article_bp.route('/photo_del')
def delete_photo():
    pid = request.args.get('pid', type=int)
    photo = Photo.query.get(pid)  # type:Photo
    info = delete_to_qiniu(photo.photo_name)
    if info.status_code == 200:
        photo.ono()
        return redirect(url_for('user.user_center'))
    else:
        return '失败了'


@article_bp.route('/pub_cmt', methods=['GET', 'POST'])
def publish_comment():
    if request.method == 'POST':
        aid = request.form.get('aid')
        cmt_ctt = request.form.get('comment')
        user_id = g.user.user_id
        cmt = Comment()
        cmt.comment = cmt_ctt
        cmt.user_id = user_id
        cmt.art_id = aid
        cmt.yes()
        return redirect(url_for('article.article_detail') + '?aid=' + aid)
    return redirect('/')


@article_bp.route('/tag')
def tag_search():
    tags = Tag.query.all()
    user = None
    uid = session.get('uid', None)
    if uid:
        user = User.query.get(uid)
    tid = request.args.get('tid', type=int)
    page = request.args.get('page', 1, type=int)

    articles = Article.query.filter(Article.tag_id == tid).paginate(page=page, per_page=3)

    return render_template('article/tag.html', **locals())


@article_bp.route('delete_cmt')
def delete_comment():
    cmt_id = request.args.get('cmt_id')
    if cmt_id:
        cmt = Comment.query.get(cmt_id)
        cmt.ono()
        return redirect(url_for('user.user_center'))

templates/article/detail.html
{% extends 'base.html' %}

{% block title %}文章详情{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/article/detail.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="w">
            <div class="detail">
                <div class="arti">
                    <h2 class="title">{{ article.title }}</h2>
                    <div class="star">
                        <div class="left">
                            <span class="author">作者</span>{{ article.author.username }}
                            &emsp;
                            <span class="pub">发布时间</span> {{ article.pub_time }}
                        </div>
                        <div class="right">
                        <span class="click">点击量
                            <i class="iconfont">&#xe83c;</i>
                            <span data-t="0">{{ article.click_num }}</span>
                        </span>

                            <span class="save">收藏
                            <i class="iconfont">&#xe83a;</i>
                           <span data-t="0">{{ article.save_num }}</span>
                        </span>

                            <span class="love">点赞量
                            <i class="iconfont">&#xe83d;</i>
                            <span data-t="0">{{ article.love_num }}</span>
                        </span>
                        </div>
                    </div>
                    <div class="content">{{ article.content | safe }}</div>
                </div> <!---->
                <hr class="line">

                <div class="comment-box">
                    <p>
                        <img src="{{ url_for('static', filename=user.avatar) }}" alt="">
                        文章评论:
                    </p>
                    <div class="form-comment">
                        <form action="{{ url_for('article.publish_comment') }}" method="post">
                            <input type="hidden" name="aid" value="{{ article.art_id }}">
                            <textarea name="comment" maxlength="255">写下你想说的，开始我们的对话
                            </textarea>
                            <div class="charCount">
                                <p>还能输入<span id="Chars">255</span>个字符</p>
                                <button type="submit" class="btn-cmt">评论</button>
                            </div>
                        </form>
                    </div>
                    <hr class="line">
                </div> <!---->

                <div class="comments"> <!---->
                    {% if comments.items %}
                        {% for comment in comments.items %}
                            <div class="cmts">
                                <div id="item_left">
                                    <img src="{% if comment.user.avatar %} {{ url_for('static',filename=comment.user.avatar) }} {% else %}{{ url_for('static',filename='images/tx.jpg') }}{% endif %}" alt="">
                                </div>
                                <div id="item_right">
                                    <p>
                                        <span class="user">{{ comment.user.username }}</span>
                                        &emsp;
                                        <span class="cmtt">{{ comment.cmt_time }}</span>
                                    </p>
                                    <p class="cmt">
                                        {{ comment.comment }}
                                    </p>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="item">
                            当前文章还没有任何评论，赶快发表意见吧～～～～
                        </div>
                    {% endif %}
                </div>

                <div class="paginate">
                    <div class="pagination">
                        <ul class="pager">
                            <li class="previous{% if not comments.has_prev %} disabled {% endif %}">
                                <a href="{{ url_for('article.article_detail') }}?page={{ comments.prev_num }}&aid={{ article.art_id }}">
                                    <span>&larr;</span> 上一页</a>
                            </li>

                            <li class="next{% if not comments.has_next %} disabled {% endif %}">
                                <a href="{{ url_for('article.article_detail') }}?page={{ comments.next_num }}&aid={{ article.art_id }}">
                                    下一页<span>&rarr;</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(function () {
            $('.save i').click(function () {  // 收藏
            })
            $('.love i').click(function () {  // 点赞
                let $this = $(this)
                let t = $this.next('span').data('t')
                console.log(t, typeof (t))
                $.get(
                    '{{ url_for('article.article_love') }}',
                    {aid: {{article.art_id}}, t: t},
                    function (data) {
                        $this.next('span').text(data.num)
                    }
                );
                if (t === 1) {
                    $this.css({'color': 'black'})
                    $this.next('span').data('t', 0)
                } else {
                    $this.css({'color': 'red'})
                    $this.next('span').data('t', 1)
                }
            });
        })
    </script>
    <script src="{{ url_for('static', filename='js/article/detail.js') }}"></script>
{% endblock %}

templates/article/tag.html
{% extends 'base.html' %}
{% block title %} 文章分类-{{ articles.tag }} {% endblock %}

{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/index.css') }}">
    <script src="{{ url_for('static', filename='js/user/index.js') }}"></script>
{% endblock %}

{% block content %}
    <div id="container">
        <div class="w">
            <div class="article-item">
                {% for article in articles.items %}
                    <div class="article">
                        <div class="title">
                            <h4>标题:
                                <a href="{{ url_for('article.article_detail') }}?aid={{ article.art_id }}">{{ article.title }}</a>
                            </h4>
                        </div>
                        <div class="author">作者: {{ article.author.username }}</div>
                        <div class="content">{{ article.content | safe }}</div>
                        <div class="star">
                            <span class="pub">发布时间: {{ article.pub_time }}</span>
                            <span class="click">点击量: {{ article.click_num }}</span>
                            <span class="save">收藏: {{ article.save }}</span>
                            <span class="love">点赞量: {{ article.love_num }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="paginate">
                <ul class="pagination">
                    <li {% if not articles.has_prev %}class="page-item disabled pre"
                        {% endif %} class="page-item pre">
                        <a href="{{ url_for('user.index') }}?page={{ articles.prev_num }}">Previous</a>
                    </li>
                    {% for page_num in range(1, articles.pages + 1) %}
                        <li {% if articles.page == page_num %}class="page-item active"
                            {% else %}class="page-item"{% endif %}>
                            <a href="{{ url_for('user.index') }}?page={{ page_num }}">{{ page_num }}</a>
                        </li>
                    {% endfor %}
                    <li {% if not articles.has_next %}class="page-item disabled next"
                        {% endif %} class="page-item next">
                        <a href="{{ url_for('user.index') }}?page={{ articles.next_num }}">Next</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}