apps/user/models.py
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime
from ..exts import db
from ..utils import BaseModel


class User(BaseModel):
    __tablename__ = 'tb_user'
    user_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(16), nullable=False)
    _password = db.Column(db.String(255), nullable=False)
    phone = db.Column(db.String(11), unique=True)
    email = db.Column(db.String(32), unique=True)
    avatar = db.Column(db.String(128))
    rgs_time = db.Column(db.DateTime, default=datetime.now)
    is_del = db.Column(db.Boolean, default=False)
    articles = db.relationship('Article', backref='author', lazy=True)
    comments = db.relationship('Comment', backref='user')

    @property
    def password(self):
        # return self._password
        raise Exception('Access Not Allowed')

    @password.setter
    def password(self, pwd):
        self._password = generate_password_hash(pwd)

    def check_pwd(self, pwd):
        return check_password_hash(self._password, pwd)


class Photo(BaseModel):
    __tablename__ = 'tb_photo'
    photo_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    photo_name = db.Column(db.String(128), nullable=False)
    photo_time = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('tb_user.user_id'), nullable=False)


class AboutMe(BaseModel):
    __tablename__ = 'tb_about_me'
    me_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)
    me_time = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('tb_user.user_id'))
    user = db.relationship('User', backref='about')


class MessageBoard(BaseModel):
    __tablename__ = 'tb_msg_board'
    bd_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.String(255), nullable=False)
    bd_time = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('tb_user.user_id'), nullable=True)
    user = db.relationship('User', backref='messages')

apps/article/views.py
from flask import Blueprint, render_template
from flask import url_for, g
from flask import jsonify, request
from flask import redirect, session
from ..utils import upload_to_qiniu, delete_to_qiniu
from .models import Article, Tag, Comment
from ..user.models import Photo, User

article_bp = Blueprint('article', __name__, url_prefix='/article')


@article_bp.route('/publish', methods=['GET', 'POST'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        tag_id = request.form.get('tag')
        content = request.form.get('content')
        article = Article()
        article.title = title
        article.tag_id = tag_id
        article.content = content
        article.user_id = g.user.user_id
        article.yes()
        return redirect(url_for('user.index'))
    return redirect(url_for('user.user_center'))


@article_bp.route('/detail')
def article_detail():
    article_id = request.args.get('aid')
    article = Article.query.get(article_id)
    user = None
    tags = Tag.query.all()
    uid = session.get('uid', None)
    if uid:
        user = User.query.get(uid)
    page = request.args.get('page', 1, type=int)
    comments = Comment.query.filter(Comment.art_id == article_id).order_by(-Comment.cmt_time).paginate(page=page, per_page=5)

    return render_template('article/detail.html', article=article, tags=tags, user=user, comments=comments)


@article_bp.route('/love')
def article_love():  # 点赞
    aid = request.args.get('aid', type=int)
    t = request.args.get('t', type=int)
    article = Article.query.get(aid)  # type: Article

    if t == 1:
        article.love_num -= 1
    else:
        article.love_num += 1
    article.yes()
    return jsonify({
        'num': article.love_num
    })


@article_bp.route('/photo', methods=['GET', 'POST'])
def photo_album():
    if request.method == 'POST':
        pic = request.files.get('photo')
        ret, info = upload_to_qiniu(pic)
        if info.status_code == 200:
            photo = Photo()
            photo.photo_name = ret['key']
            photo.user_id = g.user.user_id
            photo.yes()
            return redirect(url_for('user.user_center'))
        return 'post'
    return 'get'


@article_bp.route('/photo_del')
def delete_photo():
    pid = request.args.get('pid', type=int)
    photo = Photo.query.get(pid)  # type:Photo
    info = delete_to_qiniu(photo.photo_name)
    if info.status_code == 200:
        photo.ono()
        return redirect(url_for('user.user_center'))
    else:
        return '失败了'


@article_bp.route('/pub_cmt', methods=['GET', 'POST'])
def publish_comment():
    if request.method == 'POST':
        aid = request.form.get('aid')
        cmt_ctt = request.form.get('comment')
        user_id = g.user.user_id
        cmt = Comment()
        cmt.comment = cmt_ctt
        cmt.user_id = user_id
        cmt.art_id = aid
        cmt.yes()
        return redirect(url_for('article.article_detail') + '?aid=' + aid)
    return redirect('/')


@article_bp.route('/tag')
def tag_search():
    tags = Tag.query.all()
    user = None
    uid = session.get('uid', None)
    if uid:
        user = User.query.get(uid)
    tid = request.args.get('tid', type=int)
    page = request.args.get('page', 1, type=int)

    articles = Article.query.filter(Article.tag_id == tid).paginate(page=page, per_page=3)

    return render_template('article/tag.html', **locals())


@article_bp.route('delete_cmt')
def delete_comment():
    cmt_id = request.args.get('cmt_id')
    if cmt_id:
        cmt = Comment.query.get(cmt_id)
        cmt.ono()
        return redirect(url_for('user.user_center'))

apps/user/views.py
import os.path
from flask import Blueprint, render_template
from flask import url_for, g, current_app
from flask import jsonify, request
from flask import redirect, session
from flask_mail import Message
from itsdangerous import URLSafeTimedSerializer, SignatureExpired, BadSignature
from werkzeug.datastructures import FileStorage
from werkzeug.utils import secure_filename

from ..exts import mail
from ..cfg import Config
from random import randint
from .models import User, Photo, AboutMe, MessageBoard
from ..article.models import Tag, Article

user_bp = Blueprint('user', __name__, url_prefix='/user')

allowed_path = [
    '/user/center.html', '/user/update', '/article/publish',
    '/article/photo', '/user/photos.html', '/article/photo_del',
    '/article/pub_cmt', '/user/aboutme', '/user/showme',
]


@user_bp.before_app_request
def before_you_request():
    if request.path in allowed_path:
        uid = session.get('uid')
        if not uid:
            return render_template('user/login.html')
        else:
            user = User.query.get(uid)
            g.user = user


@user_bp.after_app_request
def after_you_request(response):
    return response


@user_bp.route('/', endpoint='index')
def index():
    uid = session.get('uid')
    page = request.args.get('page', 1, type=int)
    tags = Tag.query.all()
    pagination = Article.query.order_by(-Article.pub_time).paginate(page=page, per_page=3)
    if uid:
        user = User.query.get(uid)
        return render_template('user/index.html', user=user, pagination=pagination, tags=tags)
    else:
        return render_template('user/index.html', pagination=pagination, tags=tags)


@user_bp.route('/register.html', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        if request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            pwd = request.form.get('pwd')
            phone = request.form.get('phone')
            email = request.form.get('email')
            if password == pwd:
                user = User()
                user.username = username
                user.password = password
                user.phone = phone
                user.email = email
                user.yes()
                return redirect('/')
    return render_template('user/register.html')


@user_bp.route('/protocol')
def must_protocol():
    return render_template('user/bwtk.html')


@user_bp.route('/verify_phone')
def check_phone():
    phone_num = request.args.get('phoneNum')
    user = User.query.filter(User.phone == phone_num).all()
    if user:
        return jsonify({
            'status': 400,
            'msg': '此号码已被注册',
            'url': f'{request.url}',
        })
    else:
        return jsonify({
            'status': 200,
            'msg': '此号码可用',
            'url': f'{request.url}',
        })


@user_bp.route('/verify_email')
def check_email():
    email = request.args.get('email')
    user = User.query.filter(User.email == email).all()
    if user:
        return jsonify({
            'code': 400,
            'msg': '该邮箱已被注册',
            'url': f'{request.url}',
        })
    else:
        return jsonify({
            'code': 200,
            'msg': '该邮箱可用',
            'url': f'{request.url}',
        })


def save_captcha_to_session(email, captcha):
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    token = s.dumps(captcha, salt='email-captcha')
    session[f'captcha_{email}'] = token


def verify_captcha_from_session(email, captcha):
    s = URLSafeTimedSerializer(current_app.config['SECRET_KEY'])
    token = session.get(f'captcha_{email}')
    try:
        data = s.loads(token, salt='email-captcha', max_age=300)  # 假设验证码5分钟内有效
        return data == captcha
    except SignatureExpired:
        return False
    except BadSignature:
        return False


@user_bp.route('/email_capcha')
def send_email_capcha():
    email = request.args.get('email')
    random_num = randint(100000, 999999)
    save_captcha_to_session(email, random_num)

    try:
        msg = Message(
            subject="邮箱验证码",
            recipients=[email, ],
            html=f"""<table><tbody><tr height="40">
        <td style="padding-left:25px;padding-right:25px;font-size:18px;font-family:'微软雅黑','黑体',arial;">
            尊敬的 <a href="mailto:{email}" rel="noopener" target="_blank">{email}</a> ：
        </td></tr><tr height="15"><td></td></tr><tr height="30">
        <td style="padding-left:55px;padding-right:55px;font-family:'微软雅黑','黑体',arial;font-size:14px;line-height:20px;">
            您的账户<a href="{email}" rel="noopener" target="_blank">{email}</a> 
            正在获取身份验证, 验证码 {random_num} , 5 分钟内有效。
            </td></tr><tr height="20"><td></td></tr>
            <tr><td style="padding-left:55px;padding-right:55px;font-family:'微软雅黑','黑体',arial;font-size:14px;">
            此致<br>本站作者</td></tr><tr height="50"><td></td></tr></tbody></table>"""
        )
        mail.send(message=msg)
        return jsonify({
            'status': 200,
            'msg': '验证码发送成功'
        })
    except Exception as e:
        return jsonify({
            'status': 400,
            'msg': '验证码发送失败'
        })


@user_bp.route('/login.html', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        f = request.args.get('f')
        if f == '1':
            username = request.form.get("username")
            password = request.form.get("password")
            users = User.query.filter(User.username == username).all()
            for user in users:
                if user.check_pwd(password):
                    session['uid'] = user.user_id
                    return redirect('/')
            else:
                return render_template('user/login.html', msg='用户名或密码有误')

        elif f == '2':
            email = request.form.get('email')
            random_num = request.form.get('yzm', type=int)
            user = User.query.filter(User.email == email).first()
            if user and verify_captcha_from_session(email, random_num):
                session['uid'] = user.user_id
                return redirect(url_for('user.index'))
            else:
                return render_template('user/login.html', msg='邮箱或验证码有误')
    return render_template('user/login.html')


@user_bp.route('/logout')
def logout():
    session.clear()
    return redirect('/')


@user_bp.route('/center.html')
def user_center():
    tags = Tag.query.all()
    photos = Photo.query.filter(Photo.user_id == g.user.user_id).all()
    return render_template('user/center.html', user=g.user, tags=tags, photos=photos)


image_suffix = ['jpg', 'gif', 'png', 'webp']


@user_bp.route('/update', methods=['GET', 'POST'])
def user_update():
    if request.method == 'POST':
        username = request.form.get('username')
        phone = request.form.get('phone')
        email = request.form.get('email')
        icon = request.files.get('icon')  # type:FileStorage
        avatar_path = None
        if icon:
            icon_name = icon.filename
            suffix = icon_name.split('.')[1]
            if suffix.lower() in icon_name:
                icon_name = secure_filename(icon_name)
                file_path = os.path.join(Config.ICON_DIR, icon_name)
                icon.save(file_path)
                avatar_path = os.path.join('uploads/icon/', icon_name)
            else:
                return render_template('user/center.html', user=g.user, msg='图片格式不对')
        else:
            avatar_path = g.user.avatar if g.user.avatar else None
        user = g.user
        user.username = username
        user.phone = phone
        user.email = email
        user.avatar = avatar_path
        user.yes()
        return redirect(url_for('user.user_center'))
    else:
        return render_template('user/center.html')


@user_bp.route('/photos.html')
def my_photo():
    page = request.args.get('page', 1, type=int)
    photos = Photo.query.paginate(page=page, per_page=1)
    return render_template('user/photos.html', photos=photos, user=g.user)


@user_bp.route('/aboutme', methods=['GET', 'POST'])
def about_me():
    content = request.form.get('about')
    print(content)
    has_me = AboutMe.query.filter_by(user_id=g.user.user_id).first()
    if has_me.content:
        has_me.content = content
        has_me.yes()
    else:
        me = AboutMe()
        me.content = content
        me.user_id = g.user.user_id
        me.yes()
    return render_template('user/aboutme.html', user=g.user)


@user_bp.route('/showme')
def show_about_me():
    return render_template('user/aboutme.html', user=g.user)


@user_bp.route('/board', methods=['GET', 'POST'])
def show_board():
    uid = session.get('uid', None)
    user = None
    if uid:
        user = User.query.get(uid)
    page = request.args.get('page', 1, type=int)
    boards = MessageBoard.query.order_by(-MessageBoard.bd_time).paginate(page=page, per_page=5)
    if request.method == 'POST':
        content = request.form.get('board')
        mb = MessageBoard()
        mb.content = content
        if uid:
            mb.user_id = uid
        mb.yes()
        return redirect(url_for('user.show_board'))
    return render_template('user/board.html', user=user, boards=boards)


@user_bp.route('/del_bd')
def delete_board():
    bid = request.args.get('bid', type=int)
    if bid:
        mb = MessageBoard.query.get(bid)
        mb.ono()
        return redirect(url_for('user.user_center'))

templates/user/aboutme.html
{% extends 'base.html' %}

{% block title %}关于我{% endblock %}

{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/aboutme.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="w me">
            <div class="me-info">
                {% if not user.about %}
                    用户中心设置更多关于我的信息～～～～
                {% else %}
                    {{ user.about[0].content | safe }}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/center.html
{% extends 'base.html' %}

{% block title %}用户中心{% endblock %}
{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/center.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="w">
            <header class="header">
                <ul class="top-head">
                    <li>用户信息修改</li>
                    <li>发表文章</li>
                    <li>管理相册</li>
                    <li>管理留言</li>
                    <li>管理评论</li>
                    <li>关于我设置</li>
                </ul>
            </header>

            <section class="section">
                <!--用户信息修改-->
                <div class="middle">
                    <h2 class="user-info">用户信息修改</h2>
                    <form action="{{ url_for('user.user_update') }}" method="post" enctype="multipart/form-data">
                        <div class="form-item">
                            <label for="Username" class="form-label">用户名</label>
                            <input type="text" name="username" class="form-control" id="Username"
                                   value="{{ g.user.username }}">
                        </div>
                        <div class="form-item">
                            <label for="PhoneNum" class="form-label">手机号码</label>
                            <input type="tel" name="phone" class="form-control" id="PhoneNum"
                                   value="{{ g.user.phone }}">
                        </div>
                        <div class="form-item">
                            <label for="Email" class="form-label">邮箱</label>
                            <input type="email" name="email" class="form-control" id="Email" value="{{ g.user.email }}">
                        </div>
                        <div class="form-item">
                            <label for="IconFile" class="form-label">上传头像</label>
                            <input type="file" name="icon" class="file-control" id="IconFile">
                        </div>
                        <div class="icon">
                            <img src="{% if user.avatar %}
                            	{{ url_for('static', filename=user.avatar) }}
                            {% else %}
                            	{{ url_for('static', filename='images/tx.png') }}
                            {% endif %} " alt="">
                        </div>
                        <div class="form-button">
                            <button type="submit" class="btn btn-primary">用户信息修改</button>
                        </div>
                    </form>
                </div>
                <!--发表文章-->
                <div class="middle">
                    <form action="{{ url_for('article.publish_article') }}" method="post">
                        <div class="form-item">
                            <input type="text" name="title" class="form-control" placeholder="文章标题">
                        </div>
                        <div class="form-item">
                            <select class="form-control" name="tag">
                                <option value="0">选择分类</option>
                                {% for tag in tags %}
                                    <option value="{{ tag.tag_id }}">{{ tag.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-item">
                            <textarea name="content" class="rich-text"></textarea>
                        </div>
                        <div class="form-button">
                            <button type="submit" class="btn-primary art">发布文字</button>
                        </div>
                    </form>
                </div>

                <!--管理相册-->
                <div class="middle pic">
                    <form action="{{ url_for('article.photo_album') }}" method="post" enctype="multipart/form-data">
                        <div class="form-item">
                            <label for="formFile" class="form-label">图片上传</label>
                            <input type="file" name="photo" class="file-control" id="Photo">
                            <input type="submit" value="上传图片" class="btn-upload btn-primary">
                        </div>
                    </form>
                    <div class="photos">
                        <h3>我的相册</h3>
                        <div class="images">
                            {% for photo in photos %}
                                <div class="img">
                                    <img src="http://senanxx2e.hn-bkt.clouddn.com/{{ photo.photo_name }}" alt="">
                                    <button class="btn-del" data-tt="{{ photo.photo_id }}">delete</button>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>

                <!--留言管理-->
                <div class="middle">
                    {% if user.messages %}
                        <table class="table">
                            <tr>
                                <th>序号</th>
                                <th>留言</th>
                                <th>时间</th>
                                <th>操作</th>
                            </tr>
                            {% for message in user.messages %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>{{ message.content }}</td>
                                    <td>{{ message.bd_time }}</td>
                                    <td class="del-msg">
                                        <a href="{{ url_for('user.delete_board') }}?bid={{ message.bd_id }}">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}

                        </table>
                    {% else %}
                        <p>还没有如何内容, 赶紧去留言区吹牛吧</p>
                    {% endif %}
                </div>

                <!--评论管理-->
                <div class="middle">
                    {% if user.comments %}
                        <table class="table">
                            <tr>
                                <th>序号</th>
                                <th>评论</th>
                                <th>时间</th>
                                <th>操作</th>
                            </tr>
                            {% for comment in user.comments %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>{{ comment.comment }}</td>
                                    <td>{{ comment.cmt_time }}</td>
                                    <td class="del-msg">
                                        <a href="{{ url_for('article.delete_comment') }}?cmt_id={{ comment.cmt_id }}">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    {% else %}
                        <p>还没有如何的评论</p>
                    {% endif %}
                </div>

                <!--关于我-->
                <div class="middle">
                    <form action="{{ url_for('user.about_me') }}" method="post">
                        <div class="form-item">
                            <textarea name="about" class="rich-text"></textarea>
                        </div>
                        <div class="form-button">
                            <button type="submit" class="btn-primary">更改我的</button>
                        </div>
                    </form>
                </div>
            </section>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='tinymce/tinymce.min.js') }}"></script>
    <script>
        window.addEventListener('load', function () {
            tinymce.init({
                selector: '.rich-text',
                width: 900,
                {#height: 600,#}
                language: 'zh_CN', //调用放在langs文件夹内的语言包
                plugins: 'lists,advlist print preview searchreplace autolink directionality visualblocks visualchars fullscreen image link \
media template code codesample table charmap hr pagebreak nonbreaking anchor insertdatetime advlist lists wordcount imagetools textpattern help emoticons autosave autoresize formatpainter',
                toolbar: 'code undo redo restoredraft | cut copy paste pastetext | forecolor backcolor bold italic underline strikethrough link anchor | alignleft aligncenter alignright alignjustify outdent indent | \
styleselect formatselect fontselect fontsizeselect | bullist numlist | blockquote subscript superscript removeformat | \
table image media charmap emoticons hr pagebreak insertdatetime print preview | fullscreen | lineheight formatpainter',
                fontsize_formats: '12px 14px 16px 18px 24px 36px 48px 56px 72px',
                font_formats: '微软雅黑=Microsoft YaHei,Helvetica Neue,PingFang SC,sans-serif;苹果苹方=PingFang SC,Microsoft YaHei,sans-serif;宋体=simsun,serif;仿宋体=FangSong,serif;黑体=SimHei,sans-serif;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Book Antiqua=book antiqua,palatino;',
                importcss_append: true,
                skin: 'oxide-dark',
                images_upload_base_path: '/static/uploads/photo', //图片存放目录
                images_upload_handler: function (blobInfo, success, failure, progress) {
                    let formDate = new FormData();
                    formDate.append('file', blobInfo.blob(), blobInfo.filename);
                    fetch(
                        '/article/photo',
                        {
                            method: 'POST',
                            body: formDate
                        }
                    ).then(response => response.json()).then(data => {
                        success(data.image_usl);
                    })
                }
            });

            let editors = tinymce.editors;

            let art = document.querySelector('.btn-primary.art');
            art.addEventListener('click', function (ev) {
                let form2 = document.querySelector('.middle:nth-child(2)>form');
                let form_data = serialize(form2, {empty: true, hash: true});
                console.log(form_data)

                if (form_data.title.trim() === '') {
                    ev.preventDefault()
                }
                if (form_data.tag === '0') {
                    ev.preventDefault()
                }
                let content = editors[0].getContent()
                if (!content.trim()) {
                    ev.preventDefault()
                }
            })
        })
    </script>
    <script src="{{ url_for('static', filename='js/user/center.js') }}"></script>
{% endblock %}

templates/user/me.html
{% extends 'base.html' %}

{% block title %}关于我{% endblock %}

{% block content %}
    <div class="container">
        <div class="w about-me">

        </div>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block title %} 用户注册 {% endblock title %}

{% block links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user/register.css') }}">
    <script src="{{ url_for('static', filename='js/user/register.js') }}"></script>
{% endblock %}

{% block content %}
    <div id="container">
        <div class="w">
            <h1>用户注册</h1>
            <div class="form">
                <form action="{{ url_for('user.register') }}" method="post">
                    <div class="form-group">
                        <label for="inputUsername" class="form-label">用户名</label>
                        <div class="form-input">
                            <input name="username" minlength="2" maxlength="10" required type="text" id="inputUsername" placeholder="请输入用户名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword" class="form-label">密码</label>
                        <div class="form-input">
                            <input name="password" minlength="2" maxlength="16" required type="password" id="inputPassword" placeholder="请输入密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputConfire" class="form-label">确认密码</label>
                        <div class="form-input">
                            <input name="pwd" required type="password" id="inputConfire" placeholder="请确认密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPhone" class="form-label">手机号码</label>
                        <div class="form-input">
                            <input name="phone" required type="tel" id="inputPhone" placeholder="请输入手机号码">
                            <span class="tips"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail" class="form-label">邮箱</label>
                        <div class="form-input">
                            <input name="email" required type="email" id="inputEmail" placeholder="请输入邮箱">
                            <span class="tips"></span>
                        </div>
                    </div>
                    <div class="agreement">
                        <input type="checkbox" required> 我已阅读并同意
                        <a href="{{ url_for('user.must_protocol') }}" target="_blank">《本站霸王条款》</a>
                    </div>
                    <div class="form-btn">
                        <button type="submit" class="btn-primary">Sign in</button>
                        <button type="reset" class="btn-primary">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('#inputPhone').blur(function () {
            let phoneNum = $(this).val()
            let spanEle = $(this).next('span')
            if (phoneNum.length === 11) {
                spanEle.text('')
                $.get(
                    '{{ url_for("user.check_phone") }}',
                    {phoneNum},
                    function (data) {
                        console.log(data)
                        console.log(data.url)
                        if (data.status !== 200) {
                            spanEle.css({'color': '#ff0011', 'font-size': 12})
                            spanEle.html(data.msg)
                        }
                    }
                )
            } else {
                spanEle.css({'color': '#ff0011', 'font-size': 12})
                spanEle.html('手机号码格式不规范')
            }
        });

        $('#inputEmail').blur(function () {
            let email = $(this).val()
            let spanEle = $(this).next('span')
            if (/^[1-9]\d{3,10}@qq\.com$/.test(email)) {
                spanEle.text('')
                $.get(
                    '{{ url_for("user.check_email") }}',
                    {email},
                    function (data) {
                        console.log(data)
                        console.log(data.url)
                        if (data.code !== 200) {
                            spanEle.css({'color': '#ff0011', 'font-size': 12})
                            spanEle.html(data.msg)
                        }
                    }
                )
            } else {
                spanEle.css({'color': '#ff0011', 'font-size': 12})
                spanEle.html('qq邮箱格式不对')
            }
        });
    </script>
{% endblock %}